import { SectorMain } from "./Sector";
export interface SP_BUYOUTS {
    buyOut_Id: string;
    businessLocation_Id: string | null;
    country_Ids: string | null;
    city_Id: string | null;
    pref_Id: string | null;
    transactionType_Id: string | null;
    valuationPreferenceFrom: number | null;
    valuationPreferenceTo: number | null;
    investmentValueFrom: number | null;
    investmentValueTo: number | null;
    revenue_Id: string | null;
    ebitda: number | null;
    netProfit: number | null;
    isFinancingRequired: boolean | null;
    property_Id: string | null;
    propertyValueFrom: number | null;
    propertyValueTo: number | null;
    transactionRole_Id: string | null;
    isMendate: boolean | null;
    userId: string | null;
    status: string | null;
    description: string | null;
    type: string | null;
    subType: string | null;
    isPublic: boolean | null;
    isAccepted: boolean | null;
    isApproved: boolean | null;
    isFeatured: boolean | null;
    businessLocation: string | null;
    property: string | null;
    role: string | null;
    city: string | null;
    ownerShipPreference: string | null;
    transactionType: string | null;
    revenuePreference: string | null;
    userName: string | null;
    sectors: string | null;
    countriesInterested: string | null;
    isActive: boolean | null;
    isDeleted: boolean | null;
    created_Date: string;
    updated_Date: string;
    created_By: string;
    updated_By: string;
    sectorsArray: SectorMain[];
}